//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.MaterialInventoryServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaterialInventoryServiceRef.IMaterialInventoryLib")]
    public interface IMaterialInventoryLib {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialInventoryLib/GetMaterialInventoryData", ReplyAction="http://tempuri.org/IMaterialInventoryLib/GetMaterialInventoryDataResponse")]
        string GetMaterialInventoryData(string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialInventoryLib/GetMaterialInventoryData", ReplyAction="http://tempuri.org/IMaterialInventoryLib/GetMaterialInventoryDataResponse")]
        System.Threading.Tasks.Task<string> GetMaterialInventoryDataAsync(string Type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaterialInventoryLibChannel : ClientApp.MaterialInventoryServiceRef.IMaterialInventoryLib, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialInventoryLibClient : System.ServiceModel.ClientBase<ClientApp.MaterialInventoryServiceRef.IMaterialInventoryLib>, ClientApp.MaterialInventoryServiceRef.IMaterialInventoryLib {
        
        public MaterialInventoryLibClient() {
        }
        
        public MaterialInventoryLibClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialInventoryLibClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialInventoryLibClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialInventoryLibClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMaterialInventoryData(string Type) {
            return base.Channel.GetMaterialInventoryData(Type);
        }
        
        public System.Threading.Tasks.Task<string> GetMaterialInventoryDataAsync(string Type) {
            return base.Channel.GetMaterialInventoryDataAsync(Type);
        }
    }
}
