//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.ShoppingServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WholeSaleDealersInfo", Namespace="http://schemas.datacontract.org/2004/07/Rameshkartik.WCFSamples.OnlineShoppingSer" +
        "vice.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientApplication.ShoppingServiceProxy.WholeSaleDealersInfoDetailed))]
    public partial class WholeSaleDealersInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DealerSinceField;
        
        private string LocationofDealerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealerName {
            get {
                return this.DealerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerNameField, value) != true)) {
                    this.DealerNameField = value;
                    this.RaisePropertyChanged("DealerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DealerSince {
            get {
                return this.DealerSinceField;
            }
            set {
                if ((this.DealerSinceField.Equals(value) != true)) {
                    this.DealerSinceField = value;
                    this.RaisePropertyChanged("DealerSince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LocationofDealer {
            get {
                return this.LocationofDealerField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationofDealerField, value) != true)) {
                    this.LocationofDealerField = value;
                    this.RaisePropertyChanged("LocationofDealer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WholeSaleDealersInfoDetailed", Namespace="http://schemas.datacontract.org/2004/07/Rameshkartik.WCFSamples.OnlineShoppingSer" +
        "vice.Contracts")]
    [System.SerializableAttribute()]
    public partial class WholeSaleDealersInfoDetailed : ClientApplication.ShoppingServiceProxy.WholeSaleDealersInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DealerAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealerName1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DealerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DealerSince1Field;
        
        private string LocationofDealer1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealerAddress {
            get {
                return this.DealerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerAddressField, value) != true)) {
                    this.DealerAddressField = value;
                    this.RaisePropertyChanged("DealerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DealerAge {
            get {
                return this.DealerAgeField;
            }
            set {
                if ((this.DealerAgeField.Equals(value) != true)) {
                    this.DealerAgeField = value;
                    this.RaisePropertyChanged("DealerAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealerEmail {
            get {
                return this.DealerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerEmailField, value) != true)) {
                    this.DealerEmailField = value;
                    this.RaisePropertyChanged("DealerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="DealerName")]
        public string DealerName1 {
            get {
                return this.DealerName1Field;
            }
            set {
                if ((object.ReferenceEquals(this.DealerName1Field, value) != true)) {
                    this.DealerName1Field = value;
                    this.RaisePropertyChanged("DealerName1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DealerNumber {
            get {
                return this.DealerNumberField;
            }
            set {
                if ((this.DealerNumberField.Equals(value) != true)) {
                    this.DealerNumberField = value;
                    this.RaisePropertyChanged("DealerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="DealerSince")]
        public System.DateTime DealerSince1 {
            get {
                return this.DealerSince1Field;
            }
            set {
                if ((this.DealerSince1Field.Equals(value) != true)) {
                    this.DealerSince1Field = value;
                    this.RaisePropertyChanged("DealerSince1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="LocationofDealer", IsRequired=true)]
        public string LocationofDealer1 {
            get {
                return this.LocationofDealer1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LocationofDealer1Field, value) != true)) {
                    this.LocationofDealer1Field = value;
                    this.RaisePropertyChanged("LocationofDealer1");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Rameshkartik/WCFSamples/OnlineShoppingService", ConfigurationName="ShoppingServiceProxy.OnlineShoppingService")]
    public interface OnlineShoppingService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/StockA" +
            "vailability", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/StockA" +
            "vailabilityResponse")]
        bool StockAvailability(string sModelNumber);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/StockA" +
            "vailability", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/StockA" +
            "vailabilityResponse")]
        System.Threading.Tasks.Task<bool> StockAvailabilityAsync(string sModelNumber);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/Calcul" +
            "atePrice", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/Calcul" +
            "atePriceResponse")]
        double CalculatePrice(string sModelNumber, int iQuantity, string sDeliveryLocation);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/Calcul" +
            "atePrice", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/Calcul" +
            "atePriceResponse")]
        System.Threading.Tasks.Task<double> CalculatePriceAsync(string sModelNumber, int iQuantity, string sDeliveryLocation);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/CheckD" +
            "iscountAmount", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/CheckD" +
            "iscountAmountResponse")]
        double CheckDiscountAmount(string sModelNumber, int iQuantity, string sDeliveryLocation);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/CheckD" +
            "iscountAmount", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/CheckD" +
            "iscountAmountResponse")]
        System.Threading.Tasks.Task<double> CheckDiscountAmountAsync(string sModelNumber, int iQuantity, string sDeliveryLocation);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/GetPro" +
            "ductInformation", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/GetPro" +
            "ductInformationResponse")]
        string GetProductInformation(string sModelNumber);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/GetPro" +
            "ductInformation", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/GetPro" +
            "ductInformationResponse")]
        System.Threading.Tasks.Task<string> GetProductInformationAsync(string sModelNumber);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/GetPro" +
            "ductsAvailableinStores", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/GetPro" +
            "ductsAvailableinStoresResponse")]
        string GetProductsAvailableinStores(string sModelNumber, int iQuantity, string sDeliveryLocation);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/GetPro" +
            "ductsAvailableinStores", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/GetPro" +
            "ductsAvailableinStoresResponse")]
        System.Threading.Tasks.Task<string> GetProductsAvailableinStoresAsync(string sModelNumber, int iQuantity, string sDeliveryLocation);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/CheckD" +
            "iscountAmount_NewMethod", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/CheckD" +
            "iscountAmount_NewMethodResponse")]
        double CheckDiscountAmount_NewMethod(string sModelNumber, int iQuantity, string sDeliveryLocation);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/CheckD" +
            "iscountAmount_NewMethod", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/CheckD" +
            "iscountAmount_NewMethodResponse")]
        System.Threading.Tasks.Task<double> CheckDiscountAmount_NewMethodAsync(string sModelNumber, int iQuantity, string sDeliveryLocation);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/GetWho" +
            "leSaleDealerInfo", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/GetWho" +
            "leSaleDealerInfoResponse")]
        ClientApplication.ShoppingServiceProxy.WholeSaleDealersInfo GetWholeSaleDealerInfo(string sFilterByCity);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/GetWho" +
            "leSaleDealerInfo", ReplyAction="http://Rameshkartik/WCFSamples/OnlineShoppingService/OnlineShoppingService/GetWho" +
            "leSaleDealerInfoResponse")]
        System.Threading.Tasks.Task<ClientApplication.ShoppingServiceProxy.WholeSaleDealersInfo> GetWholeSaleDealerInfoAsync(string sFilterByCity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OnlineShoppingServiceChannel : ClientApplication.ShoppingServiceProxy.OnlineShoppingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlineShoppingServiceClient : System.ServiceModel.ClientBase<ClientApplication.ShoppingServiceProxy.OnlineShoppingService>, ClientApplication.ShoppingServiceProxy.OnlineShoppingService {
        
        public OnlineShoppingServiceClient() {
        }
        
        public OnlineShoppingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlineShoppingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineShoppingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineShoppingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool StockAvailability(string sModelNumber) {
            return base.Channel.StockAvailability(sModelNumber);
        }
        
        public System.Threading.Tasks.Task<bool> StockAvailabilityAsync(string sModelNumber) {
            return base.Channel.StockAvailabilityAsync(sModelNumber);
        }
        
        public double CalculatePrice(string sModelNumber, int iQuantity, string sDeliveryLocation) {
            return base.Channel.CalculatePrice(sModelNumber, iQuantity, sDeliveryLocation);
        }
        
        public System.Threading.Tasks.Task<double> CalculatePriceAsync(string sModelNumber, int iQuantity, string sDeliveryLocation) {
            return base.Channel.CalculatePriceAsync(sModelNumber, iQuantity, sDeliveryLocation);
        }
        
        public double CheckDiscountAmount(string sModelNumber, int iQuantity, string sDeliveryLocation) {
            return base.Channel.CheckDiscountAmount(sModelNumber, iQuantity, sDeliveryLocation);
        }
        
        public System.Threading.Tasks.Task<double> CheckDiscountAmountAsync(string sModelNumber, int iQuantity, string sDeliveryLocation) {
            return base.Channel.CheckDiscountAmountAsync(sModelNumber, iQuantity, sDeliveryLocation);
        }
        
        public string GetProductInformation(string sModelNumber) {
            return base.Channel.GetProductInformation(sModelNumber);
        }
        
        public System.Threading.Tasks.Task<string> GetProductInformationAsync(string sModelNumber) {
            return base.Channel.GetProductInformationAsync(sModelNumber);
        }
        
        public string GetProductsAvailableinStores(string sModelNumber, int iQuantity, string sDeliveryLocation) {
            return base.Channel.GetProductsAvailableinStores(sModelNumber, iQuantity, sDeliveryLocation);
        }
        
        public System.Threading.Tasks.Task<string> GetProductsAvailableinStoresAsync(string sModelNumber, int iQuantity, string sDeliveryLocation) {
            return base.Channel.GetProductsAvailableinStoresAsync(sModelNumber, iQuantity, sDeliveryLocation);
        }
        
        public double CheckDiscountAmount_NewMethod(string sModelNumber, int iQuantity, string sDeliveryLocation) {
            return base.Channel.CheckDiscountAmount_NewMethod(sModelNumber, iQuantity, sDeliveryLocation);
        }
        
        public System.Threading.Tasks.Task<double> CheckDiscountAmount_NewMethodAsync(string sModelNumber, int iQuantity, string sDeliveryLocation) {
            return base.Channel.CheckDiscountAmount_NewMethodAsync(sModelNumber, iQuantity, sDeliveryLocation);
        }
        
        public ClientApplication.ShoppingServiceProxy.WholeSaleDealersInfo GetWholeSaleDealerInfo(string sFilterByCity) {
            return base.Channel.GetWholeSaleDealerInfo(sFilterByCity);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.ShoppingServiceProxy.WholeSaleDealersInfo> GetWholeSaleDealerInfoAsync(string sFilterByCity) {
            return base.Channel.GetWholeSaleDealerInfoAsync(sFilterByCity);
        }
    }
}
