//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CustomAuthorizationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomAuthorizationServiceReference.iCustomAuthorizationService")]
    public interface iCustomAuthorizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCustomAuthorizationService/PushDataIntoServer", ReplyAction="http://tempuri.org/iCustomAuthorizationService/PushDataIntoServerResponse")]
        void PushDataIntoServer(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCustomAuthorizationService/PushDataIntoServer", ReplyAction="http://tempuri.org/iCustomAuthorizationService/PushDataIntoServerResponse")]
        System.Threading.Tasks.Task PushDataIntoServerAsync(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iCustomAuthorizationServiceChannel : Client.CustomAuthorizationServiceReference.iCustomAuthorizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iCustomAuthorizationServiceClient : System.ServiceModel.ClientBase<Client.CustomAuthorizationServiceReference.iCustomAuthorizationService>, Client.CustomAuthorizationServiceReference.iCustomAuthorizationService {
        
        public iCustomAuthorizationServiceClient() {
        }
        
        public iCustomAuthorizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iCustomAuthorizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iCustomAuthorizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iCustomAuthorizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PushDataIntoServer(string value) {
            base.Channel.PushDataIntoServer(value);
        }
        
        public System.Threading.Tasks.Task PushDataIntoServerAsync(string value) {
            return base.Channel.PushDataIntoServerAsync(value);
        }
    }
}
