//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.AuthorizationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8735/Rameshkartik/WCFSamples/Authorization", ConfigurationName="AuthorizationServiceReference.IAuthorize")]
    public interface IAuthorize {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8735/Rameshkartik/WCFSamples/Authorization/IAuthorize/GetData", ReplyAction="http://localhost:8735/Rameshkartik/WCFSamples/Authorization/IAuthorize/GetDataRes" +
            "ponse")]
        bool GetData(int iRecordNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8735/Rameshkartik/WCFSamples/Authorization/IAuthorize/GetData", ReplyAction="http://localhost:8735/Rameshkartik/WCFSamples/Authorization/IAuthorize/GetDataRes" +
            "ponse")]
        System.Threading.Tasks.Task<bool> GetDataAsync(int iRecordNumber, string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthorizeChannel : ClientApp.AuthorizationServiceReference.IAuthorize, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorizeClient : System.ServiceModel.ClientBase<ClientApp.AuthorizationServiceReference.IAuthorize>, ClientApp.AuthorizationServiceReference.IAuthorize {
        
        public AuthorizeClient() {
        }
        
        public AuthorizeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorizeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetData(int iRecordNumber, string username) {
            return base.Channel.GetData(iRecordNumber, username);
        }
        
        public System.Threading.Tasks.Task<bool> GetDataAsync(int iRecordNumber, string username) {
            return base.Channel.GetDataAsync(iRecordNumber, username);
        }
    }
}
