//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.FoodInventoryServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FoodInventoryServiceRef.IFoodInventory")]
    public interface IFoodInventory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodInventory/GetFoodInventoryData", ReplyAction="http://tempuri.org/IFoodInventory/GetFoodInventoryDataResponse")]
        string GetFoodInventoryData(string sFoodType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodInventory/GetFoodInventoryData", ReplyAction="http://tempuri.org/IFoodInventory/GetFoodInventoryDataResponse")]
        System.Threading.Tasks.Task<string> GetFoodInventoryDataAsync(string sFoodType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFoodInventoryChannel : ClientApp.FoodInventoryServiceRef.IFoodInventory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FoodInventoryClient : System.ServiceModel.ClientBase<ClientApp.FoodInventoryServiceRef.IFoodInventory>, ClientApp.FoodInventoryServiceRef.IFoodInventory {
        
        public FoodInventoryClient() {
        }
        
        public FoodInventoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FoodInventoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoodInventoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoodInventoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetFoodInventoryData(string sFoodType) {
            return base.Channel.GetFoodInventoryData(sFoodType);
        }
        
        public System.Threading.Tasks.Task<string> GetFoodInventoryDataAsync(string sFoodType) {
            return base.Channel.GetFoodInventoryDataAsync(sFoodType);
        }
    }
}
