//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.OnlinePurchaseServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OnlinePurchaseServiceReference.IPurchase")]
    public interface IPurchase {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchase/PurchaseToys", ReplyAction="http://tempuri.org/IPurchase/PurchaseToysResponse")]
        decimal PurchaseToys(int iQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchase/PurchaseToys", ReplyAction="http://tempuri.org/IPurchase/PurchaseToysResponse")]
        System.Threading.Tasks.Task<decimal> PurchaseToysAsync(int iQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchase/UpdateStock", ReplyAction="http://tempuri.org/IPurchase/UpdateStockResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void UpdateStock(int iQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchase/UpdateStock", ReplyAction="http://tempuri.org/IPurchase/UpdateStockResponse")]
        System.Threading.Tasks.Task UpdateStockAsync(int iQty);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseChannel : ClientApp.OnlinePurchaseServiceReference.IPurchase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseClient : System.ServiceModel.ClientBase<ClientApp.OnlinePurchaseServiceReference.IPurchase>, ClientApp.OnlinePurchaseServiceReference.IPurchase {
        
        public PurchaseClient() {
        }
        
        public PurchaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal PurchaseToys(int iQty) {
            return base.Channel.PurchaseToys(iQty);
        }
        
        public System.Threading.Tasks.Task<decimal> PurchaseToysAsync(int iQty) {
            return base.Channel.PurchaseToysAsync(iQty);
        }
        
        public void UpdateStock(int iQty) {
            base.Channel.UpdateStock(iQty);
        }
        
        public System.Threading.Tasks.Task UpdateStockAsync(int iQty) {
            return base.Channel.UpdateStockAsync(iQty);
        }
    }
}
