//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.ServiceReferenceObject {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://http://localhost:8735/Rameshkartik/WCFSamples/Security/Principal/ServiceLi" +
        "brary", ConfigurationName="ServiceReferenceObject.ILibrary")]
    public interface ILibrary {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://http://localhost:8735/Rameshkartik/WCFSamples/Security/Principal/ServiceLi" +
            "brary/ILibrary/GetStringData", ReplyAction="http://http://localhost:8735/Rameshkartik/WCFSamples/Security/Principal/ServiceLi" +
            "brary/ILibrary/GetStringDataResponse")]
        string GetStringData(string value);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://http://localhost:8735/Rameshkartik/WCFSamples/Security/Principal/ServiceLi" +
            "brary/ILibrary/GetStringData", ReplyAction="http://http://localhost:8735/Rameshkartik/WCFSamples/Security/Principal/ServiceLi" +
            "brary/ILibrary/GetStringDataResponse")]
        System.Threading.Tasks.Task<string> GetStringDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://http://localhost:8735/Rameshkartik/WCFSamples/Security/Principal/ServiceLi" +
            "brary/ILibrary/GetIntData", ReplyAction="http://http://localhost:8735/Rameshkartik/WCFSamples/Security/Principal/ServiceLi" +
            "brary/ILibrary/GetIntDataResponse")]
        string GetIntData(int value);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://http://localhost:8735/Rameshkartik/WCFSamples/Security/Principal/ServiceLi" +
            "brary/ILibrary/GetIntData", ReplyAction="http://http://localhost:8735/Rameshkartik/WCFSamples/Security/Principal/ServiceLi" +
            "brary/ILibrary/GetIntDataResponse")]
        System.Threading.Tasks.Task<string> GetIntDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibraryChannel : ClientApp.ServiceReferenceObject.ILibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibraryClient : System.ServiceModel.ClientBase<ClientApp.ServiceReferenceObject.ILibrary>, ClientApp.ServiceReferenceObject.ILibrary {
        
        public LibraryClient() {
        }
        
        public LibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStringData(string value) {
            return base.Channel.GetStringData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetStringDataAsync(string value) {
            return base.Channel.GetStringDataAsync(value);
        }
        
        public string GetIntData(int value) {
            return base.Channel.GetIntData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetIntDataAsync(int value) {
            return base.Channel.GetIntDataAsync(value);
        }
    }
}
